apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-iris-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KarthikSaladi047/MLOps-Pipeline.git'
    # It watches the specific branch where GitHub Actions pushes updates
    targetRevision: argo
    # It looks inside the kserve/ folder for your YAML manifests
    path: kserve
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ml-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
