apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: iris-classifier
  namespace: ml-serving
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      runtime: kserve-mlserver
      modelFormat:
        name: mlflow
      storageUri: "s3://karthik-ml-models/iris/a80b5cad6ad34c4fa56119c2195fe100/model"
