apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: iris-classifier
  namespace: ml-serving
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      runtime: kserve-mlserver
      modelFormat:
        name: mlflow
      storageUri: "s3://karthik-ml-models/iris/7cae4e40dc58493b947c74810aaf24bc/model"
