apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: iris-classifier
  namespace: ml-serving
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      runtime: kserve-mlserver
      modelFormat:
        name: mlflow
      storageUri: "s3://karthik-ml-models/iris/378bf56f21f2480db2c6bd503ec2360d/model"
