name: MLOps Hybrid Pipeline

on:
  push:
    branches:
      - ui

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4

      # Build UI Image (UPDATED: SHA tagging added)

      - name: Convert Repository Name to Lowercase
        run: |
          echo "LOWERCASE_IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')/ml-ui" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push UI Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.ui
          push: true
          tags: |
            ghcr.io/${{ env.LOWERCASE_IMAGE_NAME }}:latest
            ghcr.io/${{ env.LOWERCASE_IMAGE_NAME }}:${{ github.sha }}

      - name: Set UI Image Tag
        run: |
          echo "UI_IMAGE=ghcr.io/${{ env.LOWERCASE_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      # Checkout GitOps branch

      - name: Checkout GitOps Branch
        uses: actions/checkout@v4
        with:
          ref: argo
          path: argo-repo

      # PATCH UI DEPLOYMENT

      - name: Update UI Deployment Image
        run: |
          echo "Using UI image: ${UI_IMAGE}"

          sed -i "s|image: .*ml-ui:.*|image: ${UI_IMAGE}|g" \
            argo-repo/ui/ui-deployment.yaml

      # Commit GitOps Changes

      - name: Commit GitOps Changes
        run: |
          cd argo-repo

          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

          git add ui/ui-deployment.yaml

          git diff --cached --quiet && exit 0

          git commit -m "gitops: deploy ui ${UI_IMAGE}"
          git push origin argo