apiVersion: v1
kind: Namespace
metadata:
  name: ml-serving
---
apiVersion: v1
kind: Secret
metadata:
  name: dagshub-s3-secret
  namespace: ml-serving
  annotations:
    serving.kserve.io/s3-endpoint: play.min.io
    serving.kserve.io/s3-usehttps: "true"
    serving.kserve.io/s3-region: us-east-1 # S3 clients crash without a dummy region
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "**********************"
  AWS_SECRET_ACCESS_KEY: "**********************"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
  namespace: ml-serving
secrets:
  - name: dagshub-s3-secret
